version: '3'
services:

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
          - "8080:80"
        volumes:
          - ./src:/src
          - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          - my_network
        links:
          - php

    php:
        container_name: php
        image: php:fpm
        volumes:
          - ./src:/src
        networks:
          - my_network

networks:
    my_network:
        driver: bridge